#+TITLE: Конспект PostgreSQL Основы языка SQL и Ecto
#+AUTHOR: Mikalai Seva
#+EMAIL: mikalai.seva@gmail.com
#+DESCRIPTION:
#+KEYWORDS: PostgreSQL SQL Primer Ecto Elixir
#+LANGUAGE: ru, en
#+OPTIONS: H:3 toc:2 p:t
#+OPTIONS: ^:{}
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Введение в базы данных и SQL
** Что такое базы данных
   Одним из основных понятий в теории баз данных является *модель данных*. Можно
   сказать, что она характеризует способ организации данных и основные методы
   доступа к ним. В ходе эволюции теорий и идей была разработана реляционная
   модель данных, которая сейчас и является доминирующей. Характерной чертой
   реляционных баз данных является тот факт, что данные воспринимаются
   пользователем как таблицы.

   Одним из достоинств реляционной базы данных является ее способность
   поддерживать связи между элементами данных, избавляя программиста от
   необходимости заниматься этой рутинной и очень трудоемкой работой. Работая с
   реляционными базами данных, программист избавлен от программирования на
   «атомарном» уровне, потому что современные языки для «общения» с этими базами
   данных являются декларативными.

   Система баз данных — это компьютеризированная система, предназначенная для
   хранения, переработки и выдачи информации по запросу пользователей. Такая
   система включает в себя программное и аппаратное обеспечение, сами данные, а
   также пользователей.

   Современные системы баз данных являются, как правило, многопользовательскими.
   В таких системах одновременный доступ к базе данных могут получить
   сразу несколько пользователей.

   Основным программным обеспечением является система управления базами данных.
   По-английски она называется /database management system/ (DBMS). Кроме СУБД в
   систему баз данных могут входить утилиты, средства для разработки приложений
   (программ), средства проектирования базы данных, генераторы отчетов и др.

   Пользователи систем с базами данных подразделяются на ряд категорий. Первая
   категория — это прикладные программисты. Вторая категория — это конечные
   пользователи, ради которых и выполняется вся работа. Они могут получить
   доступ к базе данных, используя прикладные программы или универсальные
   приложения, которые входят в программное обеспечение самой СУБД. Третья
   категория пользователей — это администраторы базы данных. В их обязанности
   входят: создание базы данных, выбор оптимальных режимов доступа к ней,
   разграничение полномочий различных пользователей на доступ к той или иной
   информации в базе данных, выполнение резервного копирования базы данных и
   т.д.

   Систему баз данных можно разделить на два главных компонента: сервер и
   набор клиентов (или внешних интерфейсов). Сервер — это и есть СУБД. Один
   сервер может обслуживать много клиентов.

   Современные СУБД включают в себя словарь данных. Это часть базы данных,
   которая описывает сами данные, хранящиеся в ней. Словарь данных помогает СУБД
   выполнять свои функции.
